# Generated by Django 5.2.1 on 2025-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(null=True, verbose_name=100),
        ),
    ]
