# Generated by Django 5.2.1 on 2025-05-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
